//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "message_tb")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub to_user_id: Option<i32>,
    pub from_user_id: Option<i32>,
    pub article_id: Option<i32>,
    pub comment_id: Option<i32>,
    pub create_time: Option<DateTime>,
    pub read_time: Option<DateTime>,
    pub is_read: Option<i16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
